/**
 * User Repository Interface
 *
 * Defines the contract for User data access operations.
 * Used for dependency inversion - services depend on interface, not implementation.
 */

import type { UserRole } from '@kompass/shared/constants/rbac.constants';
import type { User } from '@kompass/shared/types/entities/user';
import type {
  PaginationOptions,
  SortOptions,
} from '@kompass/shared/utils/pagination.utils';

/**
 * User Filters for querying
 */
export interface UserFilters {
  /** Filter by email (exact match) */
  email?: string;

  /** Filter by role (user must have this role) */
  role?: UserRole;

  /** Filter by active status */
  active?: boolean;

  /** Search by display name or email (partial match) */
  search?: string;
}

/**
 * User Query Options
 * Combines filters, pagination, and sorting
 */
export interface UserQueryOptions {
  /** Filters for querying */
  filters?: UserFilters;
  /** Pagination options */
  pagination?: PaginationOptions;
  /** Sort options */
  sort?: SortOptions;
}

/**
 * User Repository Interface
 *
 * All methods return User entities with full BaseEntity fields.
 * Repository handles CouchDB-specific operations (CRUD, queries).
 */
export interface IUserRepository {
  /**
   * Find user by ID
   * @param id User ID (format: user-{uuid})
   * @returns User entity or null if not found
   */
  findById(id: string): Promise<User | null>;

  /**
   * Find user by email (exact match)
   * @param email User email address
   * @returns User entity or null if not found
   */
  findByEmail(email: string): Promise<User | null>;

  /**
   * Find all users
   * @param options Query options (filters, pagination, sorting)
   * @returns Array of User entities
   */
  findAll(options?: UserQueryOptions): Promise<User[]>;

  /**
   * Count users matching filters
   * @param filters Optional filters for counting
   * @returns Total count of matching users
   */
  count(filters?: UserFilters): Promise<number>;

  /**
   * Find users by role
   * @param role UserRole to filter by
   * @returns Array of User entities with the specified role
   */
  findByRole(role: UserRole): Promise<User[]>;

  /**
   * Create a new user
   * @param user User entity without _rev (will be generated by CouchDB)
   * @returns Created User entity with _rev
   */
  create(user: Omit<User, '_rev'>): Promise<User>;

  /**
   * Update an existing user
   * @param user User entity with _rev (for optimistic locking)
   * @returns Updated User entity with new _rev
   */
  update(user: User): Promise<User>;

  /**
   * Delete a user (soft delete by setting active=false)
   * @param id User ID
   * @throws Error if user not found
   */
  delete(id: string): Promise<void>;
}
