/**
 * Customer Repository Interface
 *
 * Defines the contract for Customer data access operations.
 * Used for dependency inversion - services depend on interface, not implementation.
 */

import type { Customer } from '@kompass/shared/types/entities/customer';
import type { CustomerRating } from '@kompass/shared/types/enums';
import type {
  PaginationOptions,
  SortOptions,
} from '@kompass/shared/utils/pagination.utils';

/**
 * Customer Filters for querying
 */
export interface CustomerFilters {
  /** Filter by owner (user ID) */
  ownerId?: string;

  /** Filter by customer rating (A, B, C) */
  rating?: CustomerRating;

  /** Filter by customer type */
  customerType?: Customer['customerType'];

  /** Search by company name (partial match) */
  search?: string;

  /** Filter by VAT number (exact match) */
  vatNumber?: string;
}

/**
 * Customer Query Options
 * Combines filters, pagination, and sorting
 */
export interface CustomerQueryOptions {
  /** Filters for querying */
  filters?: CustomerFilters;
  /** Pagination options */
  pagination?: PaginationOptions;
  /** Sort options */
  sort?: SortOptions;
}

/**
 * Customer Repository Interface
 *
 * All methods return Customer entities with full BaseEntity fields.
 * Repository handles CouchDB-specific operations (CRUD, queries).
 */
export interface ICustomerRepository {
  /**
   * Find customer by ID
   * @param id Customer ID (format: customer-{uuid})
   * @returns Customer entity or null if not found
   */
  findById(id: string): Promise<Customer | null>;

  /**
   * Find all customers for a specific owner (ADM role)
   * @param ownerId User ID of the owner
   * @param options Query options (filters, pagination, sorting)
   * @returns Array of Customer entities
   */
  findByOwner(
    ownerId: string,
    options?: CustomerQueryOptions
  ): Promise<Customer[]>;

  /**
   * Find all customers (PLAN/GF roles)
   * @param options Query options (filters, pagination, sorting)
   * @returns Array of Customer entities
   */
  findAll(options?: CustomerQueryOptions): Promise<Customer[]>;

  /**
   * Count customers matching filters
   * @param ownerId Optional owner ID for ADM role filtering
   * @param filters Optional filters for counting
   * @returns Total count of matching customers
   */
  count(ownerId?: string, filters?: CustomerFilters): Promise<number>;

  /**
   * Create a new customer
   * @param customer Customer entity without _rev (will be generated by CouchDB)
   * @returns Created Customer entity with _rev
   */
  create(customer: Omit<Customer, '_rev'>): Promise<Customer>;

  /**
   * Update an existing customer
   * @param customer Customer entity with _rev (for optimistic locking)
   * @returns Updated Customer entity with new _rev
   */
  update(customer: Customer): Promise<Customer>;

  /**
   * Delete a customer
   * @param id Customer ID
   * @throws Error if customer not found
   */
  delete(id: string): Promise<void>;

  /**
   * Find customer by VAT number (exact match for duplicate detection)
   * @param vatNumber VAT number (format: DE123456789)
   * @returns Customer entity or null if not found
   */
  findByVatNumber(vatNumber: string): Promise<Customer | null>;

  /**
   * Find customers by company name (for duplicate detection)
   * Returns all customers with similar company names for fuzzy matching
   * @param companyName Company name to search for
   * @returns Array of Customer entities (may be empty)
   */
  findByCompanyName(companyName: string): Promise<Customer[]>;
}
